In [55]:
import pandas as pd
import time, datetime
df_data = pd.read_csv('/Users/wme/git/bowchen/AudioMosPredict/Audio_Mos_Predict/AllInOne.csv')
df_data.head()

netMosAvg  d2cLossAvg  e2eJitterAvg  d2cJitterAvg  e2eLossAvg  jitDepthAvg  \
0    3.97741           4           125           125           4          534   
1    3.31220          17           286           286          17         1186   
2    2.18346          31           492           492          31         2038   
3    1.06915          48           723           723          48         3032   
4    1.00000          61           958           958          61         4046   

   playSpeedAvg  
0           1.2  
1           1.0  
2           1.0  
3           1.0  
4           1.0

In [56]:
df_data

netMosAvg  d2cLossAvg  e2eJitterAvg  d2cJitterAvg  e2eLossAvg  \
0       3.97741           4           125           125           4   
1       3.31220          17           286           286          17   
2       2.18346          31           492           492          31   
3       1.06915          48           723           723          48   
4       1.00000          61           958           958          61   
5       1.00000          78          1025          1025          78   
6       1.00000          88           965           965          88   
7       3.62769          12           146           146          12   
8       2.87999          23           366           366          23   
9       1.74661          35           562           562          35   
10      1.02937          52           841           841          52   
11      1.00000          65           981           981          65   
12      1.00000          82           972           972          82   
13      2.75211          39           393           393          39   
14      3.74328          10           214           214          10   
15      2.20611          28           441           441          28   
16      1.24865          42           621           621          42   
17      1.00000          56           951           951          56   
18      1.00000          71          1099          1099          71   
19      1.00000          85          1092          1092          85   
20      3.99098           4           101           101           4   
21      3.34140          15           288           288          15   
22      2.22977          30           576           576          30   
23      1.11753          47           778           778          47   
24      1.00000          62           904           904          62   
25      1.00000          78          1104          1104          78   
26      1.00000          91           733           733          91   
27      3.67112           9           136           136           9   
28      2.82439          24           369           369          24   
29      1.61373          37           606           606          37   
...         ...         ...           ...           ...         ...   
6054    3.86139           2            24            24           2   
6055    3.96672           2            23            23           2   
6056    4.03584           1            24            24           1   
6057    3.86711           3            32            32           3   
6058    4.02074           1            25            25           1   
6059    3.99674           2            23            23           2   
6060    3.77029           5            24            24           5   
6061    3.97145           2            26            26           2   
6062    3.86474           3            25            25           3   
6063    3.86110           3            27            27           3   
6064    3.78556           5            25            25           5   
6065    3.73433           5            29            29           5   
6066    3.89121           3            24            24           3   
6067    3.90839           3            26            26           3   
6068    3.86134           4            28            28           4   
6069    3.61444           6            27            27           6   
6070    3.86074           3            28            28           3   
6071    3.86290           3            27            27           3   
6072    3.87572           4            26            26           4   
6073    3.85790           3            28            28           3   
6074    3.61730           7            30            30           7   
6075    3.86293           3            27            27           3   
6076    3.85703           4            30            30           4   
6077    3.88116           4            28            28           4   
6078    3.85917           4   

In [57]:
df_data.drop('e2eLossAvg', axis=1, inplace=True)
df_data.drop('e2eJitterAvg', axis=1, inplace=True)
df_data

netMosAvg  d2cLossAvg  d2cJitterAvg  jitDepthAvg  playSpeedAvg
0       3.97741           4           125          534          1.20
1       3.31220          17           286         1186          1.00
2       2.18346          31           492         2038          1.00
3       1.06915          48           723         3032          1.00
4       1.00000          61           958         4046          1.00
5       1.00000          78          1025         4112          1.00
6       1.00000          88           965         4184          1.00
7       3.62769          12           146         4084          1.00
8       2.87999          23           366         3224          1.00
9       1.74661          35           562         2706          1.00
10      1.02937          52           841         3373          1.00
11      1.00000          65           981         3849          1.00
12      1.00000          82           972         4065          1.00
13      2.75211          39           393         4084          1.00
14      3.74328          10           214         3677          1.00
15      2.20611          28           441         2857          1.00
16      1.24865          42           621         2512          1.00
17      1.00000          56           951         3582          1.00
18      1.00000          71          1099         4093          1.00
19      1.00000          85          1092         4090          1.00
20      3.99098           4           101         4076          1.00
21      3.34140          15           288         3386          1.00
22      2.22977          30           576         2624          1.00
23      1.11753          47           778         2968          1.00
24      1.00000          62           904         3756          1.00
25      1.00000          78          1104         4101          1.00
26      1.00000          91           733         4159          1.00
27      3.67112           9           136         4046          1.00
28      2.82439          24           369         3206          1.00
29      1.61373          37           606         2716          1.00
...         ...         ...           ...          ...           ...
6054    3.86139           2            24           92          1.14
6055    3.96672           2            23           97          1.18
6056    4.03584           1            24           99          1.08
6057    3.86711           3            32          153          1.10
6058    4.02074           1            25          102          1.14
6059    3.99674           2            23           97          1.18
6060    3.77029           5            24           95          1.20
6061    3.97145           2            26           96          1.08
6062    3.86474           3            25          104          1.10
6063    3.86110           3            27           90          1.12
6064    3.78556           5            25           96          1.18
6065    3.73433           5            29           90          1.20
6066    3.89121           3            24          100          1.06
6067    3.90839           3            26           93          1.12
6068    3.86134           4            28          105          1.14
6069    3.61444           6            27          125          1.18
6070    3.86074           3            28           89          1.06
6071    3.86290           3            27           96          1.10
6072    3.87572           4            26           94          1.14
6073    3.85790           3            28           95          1.16
6074    3.61730           7            30           92          1.20
6075    3.86293           3            27           94          1.06
6076    3.85703           4            30           94          1.08
6077    3.88116           4            28           88          1.12
6078    3.85917           4            29           92          1.14
6079    3.64327           7            30          111          1.18
6080

In [58]:
data_train =df_data.iloc[:int(df_data.shape[0] * 0.7), :]
data_test = df_data.iloc[int(df_data.shape[0] * 0.7):, :]
print(data_train.shape, data_test.shape)

(4258, 5) (1826, 5)


In [59]:
import pandas as pd
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.preprocessing import MinMaxScaler
import time
scaler = MinMaxScaler(feature_range=(-1, 1))
scaler.fit(data_train)

/Users/wme/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:323: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


MinMaxScaler(copy=True, feature_range=(-1, 1))

In [60]:
data_train = scaler.transform(data_train)
data_test = scaler.transform(data_test)

In [61]:
data_train

array([[ 0.92610654, -0.91304348, -0.81174699, -0.75482094,  1.        ],
       [ 0.60397094, -0.63043478, -0.56927711, -0.45546373,  0.66666667],
       [ 0.05736562, -0.32608696, -0.25903614, -0.06427916,  0.66666667],
       ...,
       [ 0.90171913, -0.95652174, -0.96385542, -0.95546373,  0.93333333],
       [ 0.88673123, -0.93478261, -0.9623494 , -0.95684114,  0.93333333],
       [ 0.77177724, -0.89130435, -0.96385542, -0.9600551 ,  0.76666667]])

In [89]:
from keras.layers import Input, Dense, LSTM
from keras.models import Model

from keras.layers import *
from keras.models import *
from keras.optimizers import Adam

output_dim = 1
batch_size = 256 #每轮训练模型时，样本的数量
epochs = 60 #训练60轮次
seq_len = 5
hidden_size = 128


TIME_STEPS = 5
INPUT_DIM = 5

lstm_units = 64
X_train = np.array([data_train[i : i + seq_len, :] for i in range(data_train.shape[0] - seq_len)])
y_train = np.array([data_train[i + seq_len, 0] for i in range(data_train.shape[0]- seq_len)])
X_test = np.array([data_test[i : i + seq_len, :] for i in range(data_test.shape[0]- seq_len)])
y_test = np.array([data_test[i + seq_len, 0] for i in range(data_test.shape[0] - seq_len)])

print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)

(4253, 5, 4) (4253,) (1821, 5, 4) (1821,)


In [90]:
print(X_test)

[[[ 0.90256659 -0.95652174 -0.96536145 -0.95867769]
  [ 0.89525424 -0.93478261 -0.95933735 -0.95454545]
  [ 0.89612107 -0.95652174 -0.96084337 -0.95179063]
  [ 0.80679419 -0.89130435 -0.95933735 -0.93663912]
  [ 0.89202421 -0.93478261 -0.96084337 -0.95821855]]

 [[ 0.89525424 -0.93478261 -0.95933735 -0.95454545]
  [ 0.89612107 -0.95652174 -0.96084337 -0.95179063]
  [ 0.80679419 -0.89130435 -0.95933735 -0.93663912]
  [ 0.89202421 -0.93478261 -0.96084337 -0.95821855]
  [ 0.89978208 -0.95652174 -0.94126506 -0.95224977]]

 [[ 0.89612107 -0.95652174 -0.96084337 -0.95179063]
  [ 0.80679419 -0.89130435 -0.95933735 -0.93663912]
  [ 0.89202421 -0.93478261 -0.96084337 -0.95821855]
  [ 0.89978208 -0.95652174 -0.94126506 -0.95224977]
  [ 0.87076998 -0.93478261 -0.96084337 -0.92745638]]

 ...

 [[ 0.86781114 -0.91304348 -0.95481928 -0.95684114]
  [ 0.87949637 -0.91304348 -0.95783133 -0.95959596]
  [ 0.86884746 -0.91304348 -0.9563253  -0.95775941]
  [ 0.7642954  -0.84782609 -0.95481928 -0.94903581]


In [91]:
print(y_test)

[0.89978208 0.87076998 0.88735593 ... 0.88063438 0.8847845  0.8738063 ]


In [92]:
inputs = Input(shape=(TIME_STEPS, INPUT_DIM))
#drop1 = Dropout(0.3)(inputs)

x = Conv1D(filters = 64, kernel_size = 1, activation = 'relu')(inputs)  #, padding = 'same'
#x = Conv1D(filters=128, kernel_size=5, activation='relu')(output1)#embedded_sequences
x = MaxPooling1D(pool_size = 5)(x)
x = Dropout(0.2)(x)
print(x.shape)

(?, 1, 64)


In [93]:
lstm_out = Bidirectional(LSTM(lstm_units, activation='relu'), name='bilstm')(x)
#lstm_out = LSTM(lstm_units,activation='relu')(x)
print(lstm_out.shape)

(?, 128)


In [94]:
from keras import backend as K
from keras.engine.topology import Layer
import numpy as np
from keras import initializers
# Attention GRU network  未用     
class AttLayer(Layer):
    def __init__(self, **kwargs):
        self.init = initializers.get('normal')
        #self.input_spec = [InputSpec(ndim=3)]
        super(AttLayer, self).__init__(**kwargs)

    def build(self, input_shape):
        assert len(input_shape)==128
        #self.W = self.init((input_shape[-1],1))
        self.W = self.init((input_shape[-1],))
        #self.input_spec = [InputSpec(shape=input_shape)]
        self.trainable_weights = [self.W]
        super(AttLayer, self).build(input_shape)  # be sure you call this somewhere!

    def call(self, x, mask=None):
        eij = K.tanh(K.dot(x, self.W))
        
        ai = K.exp(eij)
        weights = ai/K.sum(ai, axis=1).dimshuffle(0,'x')
        
        weighted_input = x*weights.dimshuffle(0,1,'x')
        return weighted_input.sum(axis=1)

    def get_output_shape_for(self, input_shape):
        return (input_shape[0], input_shape[-1])

In [95]:
'''
l_att = AttLayer()(lstm_out)
output = Dense(1, activation='sigmoid')(l_att)
print(output.shape)'''

"\nl_att = AttLayer()(lstm_out)\noutput = Dense(1, activation='sigmoid')(l_att)\nprint(output.shape)"

In [96]:
from keras.layers import Input, Dense, merge
from keras import layers
# ATTENTION PART STARTS HERE
attention_probs = Dense(128, activation='sigmoid', name='attention_vec')(lstm_out)
#attention_mul=layers.merge([stm_out,attention_probs], output_shape],mode='concat',concat_axis=1))
attention_mul =Multiply()([lstm_out, attention_probs])
#attention_mul = merge([lstm_out, attention_probs],output_shape=32, name='attention_mul', mode='mul')

In [97]:
output = Dense(1, activation='sigmoid')(attention_mul)
#output = Dense(10, activation='sigmoid')(drop2)

model = Model(inputs=inputs, outputs=output)
print(model.summary())

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_5 (InputLayer)            (None, 5, 4)         0                                            
__________________________________________________________________________________________________
conv1d_5 (Conv1D)               (None, 5, 64)        320         input_5[0][0]                    
__________________________________________________________________________________________________
max_pooling1d_5 (MaxPooling1D)  (None, 1, 64)        0           conv1d_5[0][0]                   
__________________________________________________________________________________________________
dropout_5 (Dropout)             (None, 1, 64)        0           max_pooling1d_5[0][0]            
__________________________________________________________________________________________________
bilstm (Bi

In [1]:
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size, shuffle=False)
y_pred = model.predict(X_test)
print('MSE Train loss:', model.evaluate(X_train, y_train, batch_size=batch_size))
print('MSE Test loss:', model.evaluate(X_test, y_test, batch_size=batch_size))
plt.plot(y_test, label='test')
plt.plot(y_pred, label='pred')
plt.legend()
plt.show()

NameError: name 'model' is not defined

In [3]:
print("Epoch 1/60 \
37312/37312 [==============================] - 3s 92us/step - loss: 0.1865 \
Epoch 2/60 \
37312/37312 [==============================] - 2s 46us/step - loss: 0.0514 \
Epoch 3/60 \
37312/37312 [==============================] - 2s 42us/step - loss: 0.0442 \
Epoch 4/60 \
37312/37312 [==============================] - 2s 44us/step - loss: 0.0439 \
Epoch 5/60 \
37312/37312 [==============================] - 1s 39us/step - loss: 0.0436 \
Epoch 6/60 \
37312/37312 [==============================] - 1s 35us/step - loss: 0.0432 \
Epoch 7/60 \
37312/37312 [==============================] - 1s 35us/step - loss: 0.0429 \
Epoch 8/60 \
37312/37312 [==============================] - 1s 39us/step - loss: 0.0426 \
Epoch 9/60 \
37312/37312 [==============================] - 1s 37us/step - loss: 0.0424 \
Epoch 10/60 \
37312/37312 [==============================] - 1s 34us/step - loss: 0.0422 \
Epoch 11/60 \
37312/37312 [==============================] - 1s 36us/step - loss: 0.0420 \
Epoch 12/60 \
37312/37312 [==============================] - 1s 40us/step - loss: 0.0419 \
Epoch 13/60 \
37312/37312 [==============================] - 1s 40us/step - loss: 0.0418 \
Epoch 14/60 \
37312/37312 [==============================] - 1s 38us/step - loss: 0.0417 \
Epoch 15/60 \
37312/37312 [==============================] - 2s 42us/step - loss: 0.0417 \
Epoch 16/60 \
37312/37312 [==============================] - 2s 45us/step - loss: 0.0416 \
Epoch 17/60 \
37312/37312 [==============================] - 1s 39us/step - loss: 0.0416 \
Epoch 18/60 \
37312/37312 [==============================] - 2s 42us/step - loss: 0.0416 \
Epoch 19/60 \
37312/37312 [==============================] - 2s 44us/step - loss: 0.0416 \
Epoch 20/60 \
37312/37312 [==============================] - 1s 35us/step - loss: 0.0416 \
Epoch 21/60 \
37312/37312 [==============================] - 1s 40us/step - loss: 0.0416 \
Epoch 22/60 \
37312/37312 [==============================] - 2s 41us/step - loss: 0.0416 \
Epoch 23/60 \
37312/37312 [==============================] - 1s 37us/step - loss: 0.0415 \
Epoch 24/60 \
37312/37312 [==============================] - 1s 35us/step - loss: 0.0416 \
Epoch 25/60 \
37312/37312 [==============================] - 1s 40us/step - loss: 0.0415 \
Epoch 26/60 \
37312/37312 [==============================] - 2s 41us/step - loss: 0.0415 \
Epoch 27/60 \
37312/37312 [==============================] - 2s 46us/step - loss: 0.0415 \
Epoch 28/60 \
37312/37312 [==============================] - 2s 47us/step - loss: 0.0415 \
Epoch 29/60 \
37312/37312 [==============================] - 2s 43us/step - loss: 0.0414 \
Epoch 30/60 \
37312/37312 [==============================] - 1s 39us/step - loss: 0.0414 \
Epoch 31/60 \
37312/37312 [==============================] - 2s 41us/step - loss: 0.0414 \
Epoch 32/60 \
37312/37312 [==============================] - 2s 42us/step - loss: 0.0414 \
Epoch 33/60 \
37312/37312 [==============================] - 1s 37us/step - loss: 0.0414 \
Epoch 34/60 \
37312/37312 [==============================] - 2s 44us/step - loss: 0.0414 \
Epoch 35/60 \
37312/37312 [==============================] - 2s 49us/step - loss: 0.0413 \
Epoch 36/60 \
37312/37312 [==============================] - 1s 40us/step - loss: 0.0413 \
Epoch 37/60 \
37312/37312 [==============================] - 1s 35us/step - loss: 0.0413 \
Epoch 38/60 \
37312/37312 [==============================] - 2s 48us/step - loss: 0.0413 \
Epoch 39/60 \
37312/37312 [==============================] - 1s 40us/step - loss: 0.0412 \
Epoch 40/60 \
37312/37312 [==============================] - 1s 38us/step - loss: 0.0413 \
Epoch 41/60 \
37312/37312 [==============================] - 2s 42us/step - loss: 0.0412 \
Epoch 42/60 \
37312/37312 [==============================] - 2s 41us/step - loss: 0.0412 \
Epoch 43/60 \
37312/37312 [==============================] - 1s 36us/step - loss: 0.0412 \
Epoch 44/60 \
37312/37312 [==============================] - 1s 40us/step - loss: 0.0412 \
Epoch 45/60 \
37312/37312 [==============================] - 2s 43us/step - loss: 0.0412 \
Epoch 46/60 \
37312/37312 [==============================] - 1s 37us/step - loss: 0.0412 \
Epoch 47/60 \
37312/37312 [==============================] - 1s 38us/step - loss: 0.0412 \
Epoch 48/60 \
37312/37312 [==============================] - 2s 43us/step - loss: 0.0412 \
Epoch 49/60 \
37312/37312 [==============================] - 1s 39us/step - loss: 0.0411 \
Epoch 50/60 \
37312/37312 [==============================] - 1s 37us/step - loss: 0.0411 \
Epoch 51/60 \
37312/37312 [==============================] - 2s 42us/step - loss: 0.0411 \
Epoch 52/60 \
37312/37312 [==============================] - 2s 43us/step - loss: 0.0411 \
Epoch 53/60 \
37312/37312 [==============================] - 1s 38us/step - loss: 0.0411 \
Epoch 54/60 \
37312/37312 [==============================] - 2s 47us/step - loss: 0.0410 \
Epoch 55/60 \
37312/37312 [==============================] - 2s 50us/step - loss: 0.0410 \
Epoch 56/60 \
37312/37312 [==============================] - 2s 43us/step - loss: 0.0410 \
Epoch 57/60 \
37312/37312 [==============================] - 2s 48us/step - loss: 0.0410 \
Epoch 58/60 \
37312/37312 [==============================] - 2s 50us/step - loss: 0.0410 \
Epoch 59/60 \
37312/37312 [==============================] - 2s 40us/step - loss: 0.0410 \
Epoch 60/60 \
37312/37312 [==============================] - 2s 45us/step - loss: 0.0410 \
37312/37312 [==============================] - 1s 20us/step \
MSE Train loss: 0.04148709757006819 \
15988/15988 [==============================] - 0s 15us/step \
MSE Test loss: 0.0005358342003804944")

Epoch 1/60 37312/37312 [==============================] - 3s 92us/step - loss: 0.1865 Epoch 2/60 37312/37312 [==============================] - 2s 46us/step - loss: 0.0514 Epoch 3/60 37312/37312 [==============================] - 2s 42us/step - loss: 0.0442 Epoch 4/60 37312/37312 [==============================] - 2s 44us/step - loss: 0.0439 Epoch 5/60 37312/37312 [==============================] - 1s 39us/step - loss: 0.0436 Epoch 6/60 37312/37312 [==============================] - 1s 35us/step - loss: 0.0432 Epoch 7/60 37312/37312 [==============================] - 1s 35us/step - loss: 0.0429 Epoch 8/60 37312/37312 [==============================] - 1s 39us/step - loss: 0.0426 Epoch 9/60 37312/37312 [==============================] - 1s 37us/step - loss: 0.0424 Epoch 10/60 37312/37312 [==============================] - 1s 34us/step - loss: 0.0422 Epoch 11/60 37312/37312 [==============================] - 1s 36us/step - loss: 0.0420 Epoch 12/60 37312/37312 [===========================